import { Store, Product, Order, Payment, User, AuditLog } from '@/types';

export const MOCK_USERS: User[] = [
  {
    id: '1',
    email: 'admin@campus.edu',
    role: 'super-admin',
    name: 'Super Admin',
  },
  {
    id: '2',
    email: 'cafe.manager@campus.edu',
    role: 'store-manager',
    storeId: 'rec-cafe',
    name: 'Cafe Manager',
  },
  {
    id: '3',
    email: 'mart.manager@campus.edu',
    role: 'store-manager',
    storeId: 'rec-mart',
    name: 'Mart Manager',
  },
  {
    id: '4',
    email: 'hut.manager@campus.edu',
    role: 'store-manager',
    storeId: 'rec-hut',
    name: 'Hut Manager',
  },
  {
    id: '5',
    email: 'sense.manager@campus.edu',
    role: 'store-manager',
    storeId: '6-sense',
    name: '6 Sense Manager',
  },
];

export const MOCK_STORES: Store[] = [
  {
    id: 'rec-cafe',
    name: 'REC CAFE',
    description: 'Coffee, Snacks & Pastries',
    icon: '☕',
    category: 'cafe',
    isActive: true,
    operatingHours: {
      days: 'Mon - Fri',
      openTime: '08:00 AM',
      closeTime: '08:00 PM',
    },
    createdAt: new Date().toISOString(),
    managerId: '2',
  },
  {
    id: 'rec-mart',
    name: 'REC MART',
    description: 'Essentials & Groceries',
    icon: '🛒',
    category: 'mart',
    isActive: true,
    operatingHours: {
      days: 'Mon - Fri',
      openTime: '08:00 AM',
      closeTime: '08:00 PM',
    },
    createdAt: new Date().toISOString(),
    managerId: '3',
  },
  {
    id: 'rec-hut',
    name: 'REC HUT',
    description: 'Meals & Beverages',
    icon: '🍱',
    category: 'restaurant',
    isActive: true,
    operatingHours: {
      days: 'Mon - Fri',
      openTime: '08:00 AM',
      closeTime: '08:00 PM',
    },
    createdAt: new Date().toISOString(),
    managerId: '4',
  },
  {
    id: '6-sense',
    name: '6 SENSE',
    description: 'Premium Merchandise',
    icon: '🎁',
    category: 'premium',
    isActive: true,
    operatingHours: {
      days: 'Mon - Fri',
      openTime: '08:00 AM',
      closeTime: '08:00 PM',
    },
    createdAt: new Date().toISOString(),
    managerId: '5',
  },
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'prod-1',
    storeId: 'rec-cafe',
    name: 'Iced Caramel Latte',
    price: 4.5,
    category: 'Beverages',
    image: '/images/caramel-latte.jpg',
    inStock: true,
    quantity: 45,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-2',
    storeId: 'rec-cafe',
    name: 'Blueberry Muffin',
    price: 3.25,
    category: 'Pastries',
    image: '/images/blueberry-muffin.jpg',
    inStock: false,
    quantity: 0,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-3',
    storeId: 'rec-cafe',
    name: 'Double Espresso',
    price: 2.75,
    category: 'Beverages',
    image: '/images/espresso.jpg',
    inStock: true,
    quantity: 60,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-4',
    storeId: 'rec-cafe',
    name: 'Chocolate Chip Cookie',
    price: 2.5,
    category: 'Pastries',
    image: '/images/cookie.jpg',
    inStock: true,
    quantity: 30,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-5',
    storeId: 'rec-mart',
    name: 'Notebook A4',
    price: 2.99,
    category: 'Stationery',
    image: '/images/notebook.jpg',
    inStock: true,
    quantity: 120,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-6',
    storeId: 'rec-mart',
    name: 'Coca Cola 500ml',
    price: 1.5,
    category: 'Drinks',
    image: '/images/coke.jpg',
    inStock: true,
    quantity: 200,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const MOCK_ORDERS: Order[] = [
  {
    id: 'order-1',
    storeId: 'rec-cafe',
    storeName: 'REC CAFE',
    studentId: 'student-1',
    studentName: 'John Doe',
    studentEmail: 'john.doe@student.campus.edu',
    items: [
      {
        productId: 'prod-1',
        productName: 'Iced Caramel Latte',
        quantity: 2,
        price: 4.5,
        image: '/images/caramel-latte.jpg',
      },
      {
        productId: 'prod-4',
        productName: 'Chocolate Chip Cookie',
        quantity: 1,
        price: 2.5,
        image: '/images/cookie.jpg',
      },
    ],
    totalAmount: 11.5,
    paymentStatus: 'completed',
    paymentMethod: 'gpay',
    orderStatus: 'pending',
    createdAt: new Date().toISOString(),
    transactionId: 'TXN1234567890',
  },
  {
    id: 'order-2',
    storeId: 'rec-cafe',
    storeName: 'REC CAFE',
    studentId: 'student-2',
    studentName: 'Jane Smith',
    studentEmail: 'jane.smith@student.campus.edu',
    items: [
      {
        productId: 'prod-3',
        productName: 'Double Espresso',
        quantity: 1,
        price: 2.75,
        image: '/images/espresso.jpg',
      },
    ],
    totalAmount: 2.75,
    paymentStatus: 'pending',
    paymentMethod: 'gpay',
    orderStatus: 'pending',
    createdAt: new Date().toISOString(),
  },
];

export const MOCK_PAYMENTS: Payment[] = [
  {
    id: 'pay-1',
    orderId: 'order-1',
    storeId: 'rec-cafe',
    amount: 11.5,
    paymentMethod: 'gpay',
    transactionId: 'TXN1234567890',
    status: 'success',
    timestamp: new Date().toISOString(),
  },
];

export const MOCK_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'log-1',
    userId: '2',
    userName: 'Cafe Manager',
    action: 'Product marked out of stock',
    entity: 'product',
    entityId: 'prod-2',
    details: 'Blueberry Muffin marked as out of stock',
    timestamp: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: 'log-2',
    userId: '2',
    userName: 'Cafe Manager',
    action: 'Product added',
    entity: 'product',
    entityId: 'prod-4',
    details: 'Added Chocolate Chip Cookie to inventory',
    timestamp: new Date(Date.now() - 7200000).toISOString(),
  },
];

export const STORE_CATEGORIES = {
  'rec-cafe': ['Beverages', 'Pastries', 'Snacks'],
  'rec-mart': ['Stationery', 'Drinks', 'Snacks', 'Utilities'],
  'rec-hut': ['Meals', 'Beverages', 'Snacks'],
  '6-sense': ['Juices', 'Shakes', 'Chaat', 'Ice Cream'],
};
